//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int catalogID { get; set; }
        public string catalogName { get; set; }
        public int? fcatalogID { get; set; }
    }
}
